version: '3'
name: 'pci-fast'

volumes:
  pci_database_data: {}

services:
  pci_service:
    build:
      context: ./
      dockerfile: docker/service/Dockerfile
    image: krazydocker/pci-service-fastapi:latest
    container_name: pci_service_fast
    platform: linux/x86_64
    depends_on:
      - pci_db
    volumes:
      - ./app:/code/app
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "8000:8000"

  pci_db:
    build:
      context: docker/database/
      dockerfile: Dockerfile
    image: krazydocker/pci-database-postgres:latest
    container_name: pci_database_postgres
    volumes:
      - pci_database_data:/var/lib/postgresql/data
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
